### ISSUE TITLE
[Kafka connector 3.2.0] - Avro Logical Type support

### ISSUE THREAD

**Issue by PasinduGunarathne** [wso2-extensions/esb-connector-kafka#82]
**Description:**

We need to add Avro Logical Type support for the Kafka connector when producing messages. 

A sample of Kafka-Schema looks like as shown below:

`{   "name": "creation",   "type": {    "type": "long",    "logicalType": "timestamp-millis"   }  },
`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2mi-4.2.0

**Comment by ursh7n** [comment]
https://avro.apache.org/docs/1.11.0/spec.html#Logical+Types
